version: '3.8'
services:
  php-backend:
    container_name: php-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - mysql-db
    volumes:
      - ./backend:/var/www/html/
    ports:
      - 8000:80
  mysql-db:
    container_name: mysql-db
    image: mysql:5.7
    restart: always
    ports:
      - '3307:3306'
    environment:
        MYSQL_ROOT_PASSWORD: teste
        MYSQL_DATABASE: db
        MYSQL_USER: teste
        MYSQL_PASSWORD: teste